n = input()
n = n.lower()
n = n.replace(" ","")
c = set(n)
n = list(c)
n.sort()
c = str(n)
c = c.replace(",","")
c = c.replace("[","")
c = c.replace("]","")
c = c.replace("'","")
c = c.replace(" ","")
print(c)